from enum import Enum, unique


@unique
class ErrorCode(str, Enum):
    ERR_BAD_REQUEST = "ERR_BAD_REQUEST"
    ERR_ROUTE_NOT_FOUND = "ERR_ROUTE_NOT_FOUND"
    ERR_REQUEST_TOO_LARGE = "ERR_REQUEST_TOO_LARGE"
    ERR_DRAFT_NOT_FOUND = "ERR_DRAFT_NOT_FOUND"
    ERR_PROFILE_NOT_FOUND = "ERR_PROFILE_NOT_FOUND"
    ERR_JOB_NOT_FOUND = "ERR_JOB_NOT_FOUND"
    ERR_AUDIO_NOT_READY = "ERR_AUDIO_NOT_READY"
    ERR_AI_DISCLOSURE_REQUIRED = "ERR_AI_DISCLOSURE_REQUIRED"
    ERR_TEXT_EMPTY = "ERR_TEXT_EMPTY"
    ERR_TEXT_TOO_LONG = "ERR_TEXT_TOO_LONG"
    ERR_TEXT_WHITESPACE_ONLY = "ERR_TEXT_WHITESPACE_ONLY"
    ERR_SYNTHESIS_TEXT_TOO_LONG = "ERR_SYNTHESIS_TEXT_TOO_LONG"
    ERR_READING_EMPTY = "ERR_READING_EMPTY"
    ERR_READING_INVALID_CHARS = "ERR_READING_INVALID_CHARS"
    ERR_OVERRIDE_RANGE_INVALID = "ERR_OVERRIDE_RANGE_INVALID"
    ERR_OVERRIDE_SURFACE_MISMATCH = "ERR_OVERRIDE_SURFACE_MISMATCH"
    ERR_OVERRIDE_OVERLAP = "ERR_OVERRIDE_OVERLAP"
    ERR_OVERRIDE_NO_KANJI = "ERR_OVERRIDE_NO_KANJI"
    ERR_AUDIO_TOO_SHORT = "ERR_AUDIO_TOO_SHORT"
    ERR_AUDIO_TOO_LONG = "ERR_AUDIO_TOO_LONG"
    ERR_AUDIO_MOSTLY_SILENT = "ERR_AUDIO_MOSTLY_SILENT"
    ERR_AUDIO_CLIPPING = "ERR_AUDIO_CLIPPING"
    ERR_AUDIO_LEVEL_OUT_OF_RANGE = "ERR_AUDIO_LEVEL_OUT_OF_RANGE"
    ERR_FILE_TOO_LARGE = "ERR_FILE_TOO_LARGE"
    ERR_FILE_FORMAT_MISMATCH = "ERR_FILE_FORMAT_MISMATCH"
    ERR_FILE_CORRUPTED = "ERR_FILE_CORRUPTED"
    ERR_FILE_NO_AUDIO = "ERR_FILE_NO_AUDIO"
    ERR_FILE_UNSUPPORTED_FORMAT = "ERR_FILE_UNSUPPORTED_FORMAT"
    ERR_NO_CONSENT = "ERR_NO_CONSENT"
    ERR_PROFILE_ALREADY_EXISTS = "ERR_PROFILE_ALREADY_EXISTS"
    ERR_WATERMARK_NOT_DETECTED = "ERR_WATERMARK_NOT_DETECTED"
    ERR_INTERNAL = "ERR_INTERNAL"


class KoecloneError(Exception):
    """安定エラーコードを持つアプリ内例外の基底。"""

    def __init__(self, code: ErrorCode) -> None:
        self.code = code
        super().__init__(code.value)
